### ISSUE TITLE
Canonical Url vs All Lowercase Enforced .git suffix

### ISSUE THREAD

**Issue by LoganWright** [open-swift/S4#48]

**Comment by LoganWright** [comment]
Canonical URL - As spelled on repo

**Comment by LoganWright** [comment]
All lowercase, w/ .git

**Comment by Joannis** [comment]
I vote all lowercase

**Comment by Danappelxx** [comment]
I vote canonical with git
On Tue, Apr 12, 2016 at 5:55 AM Joannis Orlandos <notifications@github.com>
wrote:

> I vote all lowercase
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/open-swift/S4/issues/48#issuecomment-208891729>
>
-- 
Dan Appel

**Comment by Joannis** [comment]
Looks like it's going to be canonical :+1: 
@paulofaria feel free to close this if you think enough votes have been gathered. But me and @Obbut are convinced.

**Comment by tannernelson** [comment]
Maybe we should wait until next Tuesday as per open-swift/docs#5 ?

**Comment by paulofaria** [comment]
Just wanted add this to the discussion. That's Daniel Dunbar from the SPM team.

<img width="820" alt="screen shot 2016-04-14 at 2 39 52 pm" src="https://cloud.githubusercontent.com/assets/5126193/14537765/cb2f47a8-024e-11e6-94a6-3912f7144856.png">

**Comment by paulofaria** [comment]
https://zewo.slack.com/archives/general/p1460503823003646

**Comment by LoganWright** [comment]
I move my vote, I think it's pretty clear that we need to move to canonical 👍 

Let's start some PRs  to get some alignment on this.

**Comment by paulofaria** [comment]
@LoganWright you mean in open swift ecosystem projects?

**Comment by paulofaria** [comment]
After some discussion with@LoganWright. We still think some actions need to be taken to prevent the casing issue in `Package.swift`. Some ideas were:

- Contact projects involved with open swift and warn them about the issue and suggest them to use the canonical name. We still have few projects so that's feasible.
- Add warnings in all readmes of packages in open swift ecosystem. The warning would explain the issue and guide people to use the canonical name. If a project fails to do this own its own, we can send a PR.
- Write a blog post and expose the issue to the whole Swift community. We could also ask someone who  has a high impact in Swift community do the post. Someone like Erica Sadun?
- Write a bot (like Readme Critic) that looks for malformed `Package.swift` files and sends a PR with a correction.

Any more ideas?
